# Generated by Django 3.2.4 on 2021-07-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
        ('store', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='pickup_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_point', to='store.pickuppoint'),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room'),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='shipping_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_method', to='store.shippingmethod'),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(through='room.RoomUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='room.roomorder'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='room.roomorder'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistproductvote',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='roomwishlistproduct',
            unique_together={('room', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('user', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='roomorderline',
            unique_together={('order', 'variant')},
        ),
    ]
