# Generated by Django 3.2.5 on 2021-07-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='productreviewfile',
            name='file',
            field=models.FileField(upload_to='reviews'),
        ),
    ]
