# Generated by Django 3.2.4 on 2021-07-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0004_auto_20210723_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_products', to='store.store'),
        ),
    ]
